# Generated by Django 2.1.7 on 2019-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=200)),
                ('lesson_materials', models.TextField()),
                ('lesson_time', models.DateTimeField(verbose_name='started time')),
            ],
        ),
    ]
